### PR TITLE
Implement missing PdfDocument.Flatten() method

### PR DESCRIPTION
**Pull request by KaasKop97**
Was refactoring a .NET framework project to .NET core and stumbled upon this missing method.

Ported it over from PdfSharp.

### CODE REVIEW

**Comment by packdat** [comment]
This only sets the AcroFields to read-only. (and only on the outermost hierarchy-level, child-fields are not handled)
"Real" flattening is a completely different animal.

See this post regarding flattening in the PdfSharp-Forum: https://forum.pdfsharp.net/viewtopic.php?f=3&t=3778#p11641

If you'd like to include this change, please consider renaming the method.
Something like `MakeAcroFieldsReadOnly` or something that better describes what the method actually does.

**Comment by KaasKop97** [comment]
Whilst I agree with your point, the [orginal PdfSharp](https://github.com/empira/PDFsharp/blob/master/src/PdfSharp/Pdf/PdfDocument.cs#L900) uses the same 'Flatten' name.

Nevertheless I'd be more than happy to change the name to the one you propositioned, but I am unsure how this project looks at breaking compatibility between the original and this version?

**Comment by packdat** [comment]
I'm aware of the fact that the code was ported from the original PdfSharp.
However IMHO the original implementation is flawed and the name is misleading.
Because of that i would vote against porting this in it's current state.

What if someone comes up with a more _correct_ implementation of flattening in the future ?
Does he need to call this new method `ReallyFlatten` ?

Regarding compatibility:
Please correct me, but i would be surprised, if this library is 100% API-compatible with the original one.
One method more or less shouldn't be a big problem, especially since I assume this particular method is not used very often.

**Comment by ststeiger** [comment]
@packdat: I agree with KaasKop97.
Use the other name. 
Don't call it flatten when it doesn't flatten.

**Pull request merged**
