### PR TITLE
[WIP] Add basic tests to verify that pdfs can be created

### PR DESCRIPTION
**Pull request by Marv51**
This adds two tests, one that creates a PDF with some text content and the other creating a PDF with an image.
It verifies that the PDFs are properly written to disk and are not empty.

I have also enabled the tests to run on all versions of dotnet core.

Hope this helps.

### CODE REVIEW

**Comment by Bogdancev** [comment]
Hi Marv51

Why do you need to write files on disk? Can't it be in MemoryStream or something?

**Comment by Marv51** [comment]
I followed the existing tests a bit, but yes, MemoryStream does seem better. I'll update this.

**Comment by ststeiger** [comment]
Bogdancev@: 
Actually, when you write tests, you should probably test both cases, otherwise you don't have 100% coverage, which means the tests are essentially useless ;)

**Comment by ststeiger** [comment]
Merged.

**Comment by Bogdancev** [comment]
As I understood he was testing that actually a pdf is created by checking first bytes, and not where it was created. But I might be wrong.

**Pull request merged**
